server:
  port: 8080

spring:
    datasource:
        name: persons
        url: jdbc:mysql://localhost:3306/persons?useUnicode=true&characterEncoding=utf-8
        username: syguser
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


mybatis:
    mapper-locations: classpath:org.linlinjava.litemall.admin.mapper/*Mapper.xml
    type-aliases-package: org.linlinjava.litemall.admin.domain



pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql